### ISSUE TITLE
请问是否支持获得每个包的消息类型

### ISSUE THREAD

**Issue by mynewstart** [jmhIcoding/flowcontainer#1]
类似于包长序列，是否可以获得消息类型序列？

**Comment by jmhIcoding** [comment]
支持。例如，你想获取tls里面，那些是client hello,那些是server hello, 那么你在extension里面填入tls.handshake.type即可。
如果你想解析是否为http，DNS的就需要自己枚举感兴趣的协议类型，具体你自己使用一下就知道了。

**Comment by mynewstart** [comment]
好的，感谢回复

**Comment by jmhIcoding** [comment]
问题已解决

**Comment by jmhIcoding** [comment]
。

**Comment by jmhIcoding** [comment]
OVER
