### ISSUE TITLE
extension输出为空，或者输出乱码

### ISSUE THREAD

**Issue by Marin8161** [jmhIcoding/flowcontainer#11]
你好，所用数据为原作者的数据包，其余数据都相同只有extension不一样，
extension: {'tls.handshake.certificate': [('308206273082050fa00302010202100e8ef818d55d9736ae927ee75e910207300d06092a864886f70d01010b05003070310b300906035504061302555331153013060355040a130c446967694365727420496e6331193017060355040b13107777772e64696769636572742e636f6d312f302d06035504031326446967694365727420534841322048696768204173737572616e636520536572766572204341301e170d3230303531343030303030305a170d3230303830353132303030305a3069310b3009060355040613025553311330110603550408130a43616c69666f726e6961311330110603550407130a4d656e6c6f205061726b31173015060355040a130e46616365626f6f6b2c20496e632e3117301506035504030c0e2a2e66616365626f6f6b2e636f6d3059301306072a8648ce3d020106082a8648ce3d03010703420004524d226523b72251675cf100f206253fa2012ea97407eed01d5219f4f509eb28da877e17bdc19aafafb42be0729d2a1e4bd1a6c87025aa44a0571df72c0af058a382038d30820389301f0603551d230418301680145168ff90af0207753cccd9656462a212b859723b301d0603551d0e04160414f774f64600f9f6c58348283be5e19b362339fb8e3081b50603551d110481ad3081aa820e2a2e66616365626f6f6b2e636f6d820e2a2e66616365626f6f6b2e6e6574820b2a2e666263646e2e6e6574820b2a2e66627362782e636f6d820f2a2e6d657373656e6765722e636f6d820c66616365626f6f6b2e636f6d820d6d657373656e6765722e636f6d82102a2e6d2e66616365626f6f6b2e636f6d820e2a2e78782e666263646e2e6e6574820e2a2e78792e666263646e2e6e6574820e2a2e787a2e666263646e2e6e6574300e0603551d0f0101ff040403020780301d0603551d250416301406082b0601050507030106082b0601050507030230750603551d1f046e306c3034a032a030862e687474703a2f2f63726c332e64696769636572742e636f6d2f736861322d68612d7365727665722d67362e63726c3034a032a030862e687474703a2f2f63726c342e64696769636572742e636f6d2f736861322d68612d7365727665722d67362e63726c304c0603551d2004453043303706096086480186fd6c0101302a302806082b06010505070201161c68747470733a2f2f7777772e64696769636572742e636f6d2f4350533008060667810c01020230818306082b0601050507010104773075302406082b060105050730018618687474703a2f2f6f6373702e64696769636572742e636f6d304d06082b060105050730028641687474703a2f2f636163657274732e64696769636572742e636f6d2f446967694365727453484132486967684173737572616e636553657276657243412e637274300c0603551d130101ff0402300030820105060a2b06010401d6790204020481f60481f300f1007600b21e05cc8ba2cd8a204e8766f92bb98a2520676bdafa70e7b249532def8b905e00000172142d688d000004030047304502207181afefa12dee3c23f2c1b8a99bea91b04f8f1a0d031604795e64445640a9ce022100f8b0f652d4357eb2188e612c7b869bed8e59b89f5f4b77ed4122955afc6df63c007700f095a459f200d18240102d2f93888ead4bfe1d47e399e1d034a6b0a8aa8eb27300000172142d68a10000040300483046022100fefdb34c021043a209cfe111e95756c1f1d84287bffa452a9f7e5cd033294a10022100aa29c90e85a55c5430a41286fe0a30f1690a943b442adf698037c18a4956d135300d06092a864886f70d01010b05000382010100647d4c6b9f7a32f5c1dad09664c5d399f4ace10b0271217c1365f5aa389d625e14c5d34aa65b7910d365c31b26a84ac42f07d17bb2dafb073604fae63f6ab831133dd605bb2ae231508ff9eabafa7600fe19bfc6cfb6dd3a116547e0fb488b0673354e996fbf136d8d3d2fea8a0ab7c040cbe7f7024441c606e496ee4b406e282de58e4bd7df473f439437a50f56c829dc5ecca268982fc24ef80a4a5d238d89dab52455d7b21ab3f8e0de43dca2ad786d5110f71c8f2052ae05530763903ecaeab5dcc8fdbf85425c5956b2e3f7ce39793e8119c5e273be61f6cb24420383521fea64eb27f00e1d548b7e5dfbf332c85090180d265912eefec6060b1ed35638,308204b130820399a003020102021004e1e7a4dc5cf2f36dc02b42b85d159f300d06092a864886f70d01010b0500306c310b300906035504061302555331153013060355040a130c446967694365727420496e6331193017060355040b13107777772e64696769636572742e636f6d312b30290603550403132244696769436572742048696768204173737572616e636520455620526f6f74204341301e170d3133313032323132303030305a170d3238313032323132303030305a3070310b300906035504061302555331153013060355040a130c446967694365727420496e6331193017060355040b13107777772e64696769636572742e636f6d312f302d06035504031326446967694365727420534841322048696768204173737572616e63652053657276657220434130820122300d06092a864886f70d01010105000382010f003082010a0282010100b6e02fc22406c86d045fd7ef0a6406b27d22266516ae42409bcedc9f9f76073ec330558719b94f940e5a941f5556b4c2022aafd098ee0b40d7c4d03b72c8149eef90b111a9aed2c8b8433ad90b0bd5d595f540afc81ded4d9c5f57b786506899f58adad2c7051fa897c9dca4b182842dc6ada59cc71982a6850f5e44582a378ffd35f10b0827325af5bb8b9ea4bd51d027e2dd3b4233a30528c4bb28cc9aac2b230d78c67be65e71b74a3e08fb81b71616a19d23124de5d79208ac75a49cbacd17b21e4435657f532539d11c0a9a631b199274680a37c2c25248cb395aa2b6e15dc1dda020b821a293266f144a2141c7ed6d9bf2482ff303f5a26892532f5ee30203010001a38201493082014530120603551d130101ff040830060101ff020100300e0603551d0f0101ff040403020186301d0603551d250416301406082b0601050507030106082b06010505070302303406082b0601050507010104283026302406082b060105050730018618687474703a2f2f6f6373702e64696769636572742e636f6d304b0603551d1f044430423040a03ea03c863a687474703a2f2f63726c342e64696769636572742e636f6d2f4469676943657274486967684173737572616e63654556526f6f7443412e63726c303d0603551d200436303430320604551d2000302a302806082b06010505070201161c68747470733a2f2f7777772e64696769636572742e636f6d2f435053301d0603551d0e041604145168ff90af0207753cccd9656462a212b859723b301f0603551d23041830168014b13ec36903f8bf4701d498261a0802ef63642bc3300d06092a864886f70d01010b05000382010100188a958903e66ddf5cfc1d68ea4a8f83d6512f8d6b44169eac63f5d26e6c84998baa8171845bed344eb0b7799229cc2d806af08e20e179a4fe034713eaf586ca59717df404966bd359583dfed331255c183884a3e69f82fd8c5b98314ecd789e1afd85cb49aaf2278b9972fc3eaad5410bdad536a1bf1c6e47497f5ed9487c03d9fd8b49a098264240ebd69211a4640a5754c4f51dd6025e6baceec4809a1272fa5693d7ffbf30850630bf0b7f4eff57059d24ed85c32bfba675a8ac2d16ef7d7927b2ebc29d0b07eaaa85d301a3202841594328d281e3aaf6ec7b3b77b640628005414501ef17063edec0339b67d3612e7287e469fc120057401e70f51ec9b4', 9)]}
想请问一下这大概是什么原因

**Comment by jmhIcoding** [comment]
这个能叫乱码吗？这不明显是TLS证书的16进制吗？去我的博客看看解决方案吧，有人提了跟你一样的问题，https://jmh081701.blog.csdn.net/article/details/107148871。

**Comment by Marin8161** [comment]
您好，你给我发的这个链接显示已经不存在，想请问一下能发一个有的么，谢谢

**Comment by Marin8161** [comment]
> 这个能叫乱码吗？这不明显是TLS证书的16进制吗？去我的博客看看解决方案吧，有人提了跟你一样的问题，[https://jmh081701.blog.csdn.net/article/details/107148871。](https://jmh081701.blog.csdn.net/article/details/107148871%E3%80%82)



> 这个能叫乱码吗？这不明显是TLS证书的16进制吗？去我的博客看看解决方案吧，有人提了跟你一样的问题，[https://jmh081701.blog.csdn.net/article/details/107148871。](https://jmh081701.blog.csdn.net/article/details/107148871%E3%80%82)

您好，你给我发的这个链接显示已经不存在，想请问一下能发一个有的么，谢谢

**Comment by jmhIcoding** [comment]
> > 这个能叫乱码吗？这不明显是TLS证书的16进制吗？去我的博客看看解决方案吧，有人提了跟你一样的问题，[https://jmh081701.blog.csdn.net/article/details/107148871。](https://jmh081701.blog.csdn.net/article/details/107148871%E3%80%82)
> 
> > 这个能叫乱码吗？这不明显是TLS证书的16进制吗？去我的博客看看解决方案吧，有人提了跟你一样的问题，[https://jmh081701.blog.csdn.net/article/details/107148871。](https://jmh081701.blog.csdn.net/article/details/107148871%E3%80%82)
> 
> 您好，你给我发的这个链接显示已经不存在，想请问一下能发一个有的么，谢谢

你把最后一个句号去掉就可以访问了，
https://jmh081701.blog.csdn.net/article/details/107148871
