### ISSUE TITLE
In the return value of the extract function, the flow id of the two keys are the same

### ISSUE THREAD

**Issue by IDP-code** [jmhIcoding/flowcontainer#13]
```
from flowcontainer.extractor import extract
feature_result = extract('./5.pcap')
for key in feature_result.keys():
        print(key)
```

outputs:
```
('./5.pcap', ('tcp', 'TLSv1.3'), '0')
('./5.pcap', ('tcp', 'TCP'), '0')
```
I think this is due to the wireshark display problem caused by the tcp segment.

The zip file is the 5.pcap file.
[5.zip](https://github.com/jmhIcoding/flowcontainer/files/11220002/5.zip)

**Comment by jmhIcoding** [comment]
yes, I also nitice such a bug in the lastest version.
you can downgrade the flow container to 4.x

**Comment by Alonepeople** [comment]
您好，我第一次接触就是6.3版本，其他版本不了解。因此对于把版本降低，会不会影响最新版本和旧版本提取内容有异的问题呢？例如提取流的总个数以及具体的特征是否一致？

**Comment by jmhIcoding** [comment]
> ```
> from flowcontainer.extractor import extract
> feature_result = extract('./5.pcap')
> for key in feature_result.keys():
>         print(key)
> ```
> 
> outputs:
> 
> ```
> ('./5.pcap', ('tcp', 'TLSv1.3'), '0')
> ('./5.pcap', ('tcp', 'TCP'), '0')
> ```
> 
> I think this is due to the wireshark display problem caused by the tcp segment.
> 
> The zip file is the 5.pcap file. [5.zip](https://github.com/jmhIcoding/flowcontainer/files/11220002/5.zip)

I have fixed the bug, you can upgrade the flowcontainer to 6.5.

**Comment by jmhIcoding** [comment]
> 您好，我第一次接触就是6.3版本，其他版本不了解。因此对于把版本降低，会不会影响最新版本和旧版本提取内容有异的问题呢？例如提取流的总个数以及具体的特征是否一致？

您好，你可以更新到6.5版本试试。
