### ISSUE TITLE
解析报文中不存在的字段报错

### ISSUE THREAD

**Issue by IDP-code** [jmhIcoding/flowcontainer#14]
```
from flowcontainer.extractor import extract
feature_result = extract("./5.pcap", filter='', extension=['udp.length'])
for key in feature_result.keys():
    extensions = feature_result[key]
    print(extensions)
```
报错
```
  File "..../flowcontainer/extractor.py", line 36, in extract
    result = flow_generator.combine(result,extension)
  File "..../flowcontainer/flow_generator.py", line 29, in combine
    for packet in packets:
TypeError: 'NoneType' object is not iterable
```

由于5.pcap中都是tcp包，确实包中不包含udp.length字段。但是我理解正常应该显示extensions中有这个key，但是其value是空。
附件是5.pcap
[5.zip](https://github.com/jmhIcoding/flowcontainer/files/11316158/5.zip)

**Comment by jmhIcoding** [comment]
```
C:\Python36\lib\site-packages\flowcontainer\reader.py:114: UserWarning: Running Error : tshark parse error : 'The extension field `udp.length` has been extracted more than once at least! Please check your extension parameter!'.
  .format(ex))
Traceback (most recent call last):
  File "C:/Users/adol/fix_bugs/issue14.py", line 3, in <module>
    feature_result = extract("./5.pcap", filter='', extension=['udp.length'])
  File "C:\Python36\lib\site-packages\flowcontainer\extractor.py", line 36, in extract
    result = flow_generator.combine(result,extension)
  File "C:\Python36\lib\site-packages\flowcontainer\flow_generator.py", line 29, in combine
    for packet in packets:
TypeError: 'NoneType' object is not iterable
```

这不是明明写了错误原因：The extension field `udp.length` has been extracted more than once at least! Please check your extension parameter!'. 吗？？？

**Comment by jmhIcoding** [comment]
```
C:\Python36\lib\site-packages\flowcontainer\reader.py:114: UserWarning: Running Error : tshark parse error : 'The extension field `udp.length` has been extracted more than once at least! Please check your extension parameter!'.
  .format(ex))
Traceback (most recent call last):
  File "C:/Users/adol/fix_bugs/issue14.py", line 3, in <module>
    feature_result = extract("./5.pcap", filter='', extension=['udp.length'])
  File "C:\Python36\lib\site-packages\flowcontainer\extractor.py", line 36, in extract
    result = flow_generator.combine(result,extension)
  File "C:\Python36\lib\site-packages\flowcontainer\flow_generator.py", line 29, in combine
    for packet in packets:
TypeError: 'NoneType' object is not iterable
```

这不是明明写了错误原因：The extension field `udp.length` has been extracted more than once at least! Please check your extension parameter!'. 吗？？？

**Comment by IDP-code** [comment]
抱歉，我还是不明白为什么会提示这个错误原因。在使用中，是不要在extension parameter中添加报文中没有的字段吗？比如这里就需要预先过滤下udp流量。

**Comment by jmhIcoding** [comment]
> 抱歉，我还是不明白为什么会提示这个错误原因。在使用中，是不要在extension parameter中添加报文中没有的字段吗？比如这里就需要预先过滤下udp流量。

没有看到这句话吗？`The extension field udp.length has been extracted more than once at least! Please check your extension parameter!'.`  我在使用文档里面已经写了，会对常见的IP长度，载荷长度进行提取。如果是tcp，那么载荷长度就是tcp.length，如果是udp那么提取的就是这个udp.length。你在extension parameter再填udp.length就是在二次提取了，所以提醒你这个字段提取了两次，不要在extention parameter写udp.length了，并不是因为流里面没有这个字段。

**Comment by IDP-code** [comment]
> > 抱歉，我还是不明白为什么会提示这个错误原因。在使用中，是不要在extension parameter中添加报文中没有的字段吗？比如这里就需要预先过滤下udp流量。
> 
> 没有看到这句话吗？`The extension field udp.length has been extracted more than once at least! Please check your extension parameter!'.` 我在使用文档里面已经写了，会对常见的IP长度，载荷长度进行提取。如果是tcp，那么载荷长度就是tcp.length，如果是udp那么提取的就是这个udp.length。你在extension parameter再填udp.length就是在二次提取了，所以提醒你这个字段提取了两次，不要在extention parameter写udp.length了，并不是因为流里面没有这个字段。

好的，明白了，感谢！
