### ISSUE TITLE
tshark should not greater than 2.6.0

### ISSUE THREAD

**Issue by Binghui99** [jmhIcoding/flowcontainer#16]
there is an error shows the version of t-shark is larger than 2.6.0. But I see that the minimum version is 2.6.0. 

105 if version > __tshark_max_version__:
--> 106     raise EnvironmentError('the version of tshark (wireshark) should not be greater thant {1}, however the current version if {0}.'.format(version,__tshark_min_version__))
    107 __tshark_current_version__ = version

OSError: the version of tshark (wireshark) should not be greater thant 2.6.0, however the current version if 4.0.6.

**Comment by jmhIcoding** [comment]
The version of your wireshark must be larger than 2.6.0 and less than 4.0.x,
specially, the tshark with a version of 4.0.6 shares some different features from the tshark of 3.x, leading some unknown error for flowcontainer.
