### ISSUE TITLE
解析extension时有bug

### ISSUE THREAD

**Issue by Ezio1997** [jmhIcoding/flowcontainer#3]
虽然解析后 value = result[key] 时可通过判断 value[1]区分udp/tcp，但如果在extension加入查询 ip.proto字段会导致extract读取后的结果仅一条流，且key为 ('xxx.pcap', 'unknown', 0)。

**Comment by jmhIcoding** [comment]
你好，你使用的哪个版本的？最新版本的会检查extension参数，如果出现重复的字段提取应该会抛出异常提示才对。
flowcontainer 默认会提取ip.proto字段，你再提取这个字段就会出现错误。相同字段只能提取一次，这是tshark的限制。

**Comment by Ezio1997** [comment]
okayyy，原来今年版本还更新过，辛苦师兄
