### ISSUE TITLE
使用最新版本numpy会触发警告

### ISSUE THREAD

**Issue by pth2000** [jmhIcoding/flowcontainer#6]
在使用最新版本numpy的情况下，使用flowcontainer进行特征提取时，会触发以下警告：

`...\venv\lib\site-packages\flowcontainer\reader.py:252: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  result = np.asarray(result)
`

经研究发现，此行代码应该做一点小修改，即可避免警告：
`result = np.asarray(result, dtype=object)`

**Comment by jmhIcoding** [comment]
可。
